### ISSUE TITLE
Does not pull captchas

### ISSUE THREAD

**Issue by yochananmarqos** [dotWee/OpenKWSolver#1] opened 2015-02-26 18:45 UTC
It connects to 9kw, shows the workers & captchas in queue and shows my credits after entering my API key. However it either crashes or does nothing after tapping Start. No captcha appears.

Nexus 4
android-5.0.1_r1 (LRX22C)
OpenKWSolver beta.6

I took a per app logcat: 

---- Feb 26, 2015 11:33:31 AM ----

02-26 11:33:37.543   775  1238 W PackageManager: Failure retrieving resources for de.dotwee.openkwsolver: Resource ID #0x0

02-26 11:33:40.066   611   626 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10100000 pkg=de.dotwee.openkwsolver cmp=de.dotwee.openkwsolver/.MainActivity} from uid 10148 on display 0

02-26 11:33:40.205   611   993 I ActivityManager: Start proc de.dotwee.openkwsolver for activity de.dotwee.openkwsolver/.MainActivity: pid=673 uid=10300 gids={50300, 9997, 3003} abi=armeabi-v7a

02-26 11:33:41.518   611   641 I ActivityManager: Displayed de.dotwee.openkwsolver/.MainActivity: +1s397ms

02-26 11:34:09.536   673   673 E AndroidRuntime: Process: de.dotwee.openkwsolver, PID: 673

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:357)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:09.536   673   673 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:11.451   611   992 I WindowState: WIN DEATH: Window{19401f48 u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}

02-26 11:34:11.480   611   782 I ActivityManager: Process de.dotwee.openkwsolver (pid 673) has died

02-26 11:34:11.481   611   782 W ActivityManager: Force removing ActivityRecord{2758ed39 u0 de.dotwee.openkwsolver/.MainActivity t921}: app died, no saved state

02-26 11:34:14.704   775   775 W PackageManager: Failure retrieving resources for de.dotwee.openkwsolver: Resource ID #0x0

02-26 11:34:16.364   611  1073 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10100000 pkg=de.dotwee.openkwsolver cmp=de.dotwee.openkwsolver/.MainActivity} from uid 10148 on display 0

02-26 11:34:16.552   611   895 I ActivityManager: Start proc de.dotwee.openkwsolver for activity de.dotwee.openkwsolver/.MainActivity: pid=972 uid=10300 gids={50300, 9997, 3003} abi=armeabi-v7a

02-26 11:34:17.592   611   641 I ActivityManager: Displayed de.dotwee.openkwsolver/.MainActivity: +1s183ms

02-26 11:34:33.811   972   972 E AndroidRuntime: Process: de.dotwee.openkwsolver, PID: 972

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:357)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.811   972   972 E AndroidRuntime:    at de.dotwee.openkwsolver.MainActivity.readState(MainActivity.java:367)

02-26 11:34:33.812   611   700 I InputDispatcher: Application is not responding: Window{16d72e9d u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}.  It has been 5004.0ms since event, 5003.5ms since wait started.  Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 3.  Wait queue head age: 6656.8ms.

02-26 11:34:33.818   611   700 I WindowManager: Input event dispatching timed out sending to de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity.  Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 3.  Wait queue head age: 6656.8ms.

02-26 11:34:35.603   611   700 W InputDispatcher: channel '16d72e9d de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd

02-26 11:34:35.603   611   700 E InputDispatcher: channel '16d72e9d de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

02-26 11:34:37.512   611  1003 I WindowState: WIN DEATH: Window{16d72e9d u0 de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity}

02-26 11:34:37.512   611  1003 W InputDispatcher: Attempted to unregister already unregistered input channel '16d72e9d de.dotwee.openkwsolver/de.dotwee.openkwsolver.MainActivity (server)'

02-26 11:34:37.560   611  1448 I ActivityManager: Process de.dotwee.openkwsolver (pid 972) has died

02-26 11:34:37.560   611  1448 W ActivityManager: Force removing ActivityRecord{ac5d5f1 u0 de.dotwee.openkwsolver/.MainActivity t921}: app died, no saved state

02-26 11:34:40.042   611   636 E ActivityManager: ANR in de.dotwee.openkwsolver (de.dotwee.openkwsolver/.MainActivity)

02-26 11:34:40.043   611   636 I ActivityManager: Killing 0:de.dotwee.openkwsolver/u0a300 (adj 0): bg anr

---- Feb 26, 2015 11:35:11 AM ----

**Comment by dotWee** [comment] 2015-02-26 20:25
Couldn't reproduce the error, but it should be fixed by commit [ff82dab](https://github.com/dotWee/OpenKWSolver/commit/ff82dab609436b0e07f32fe2b9803d3e33ee3984) in new beta.7 release.

**Closed as completed by dotWee** 2015-02-26 20:25 UTC
Labels: bug
